title = "huskyCI gitleaks config"
[whitelist]
files = [
    "(.*?)(yaml|jpg|gif|doc|pdf|bin)$",
    "^vendor/(.*?)$",
    ".gitleaks.toml",
]

[allowlist]
    description = "ignore yaml files"
    files = [
        '''(.*)?yaml$'''
    ]
title = "gitleaks config"