apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-image-from-jumpbox
spec:
  workspaces:
    - name: source
  steps:
    - name: apply
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          dnf install git openssh openssh-clients -y
          cd ~
          git clone https://github.com/keunlee/wls12214-todo-app-on-ocp.git
          cd wls12214-todo-app-on-ocp
          git checkout dev
          
          mkdir ~/.ssh
          jumpbox_host=$(oc get secret jumbox-secrets -o jsonpath={.data.jumpbox_host} | base64 -d) 
          (oc get secret jumbox-secrets -o jsonpath={.data.id_ed25519} | base64 -d) > ~/.ssh/id_ed25519
          (oc get secret jumbox-secrets -o jsonpath={.data.id_ed25519.pub} | base64 -d) > ~/.ssh/id_ed25519.pub
          (oc get secret jumbox-secrets -o jsonpath={.data.known_hosts} | base64 -d) > ~/.ssh/known_hosts
          chmod 400 ~/.ssh/id_ed25519
                    
          jumpbox_host=$(oc get secret jumbox-secrets -o jsonpath={.data.jumpbox_host} | base64 -d) 
          ssh $jumpbox_host "./start-build.sh"
