apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-database
spec:
  workspaces:
    - name: source
  steps:
    - name: apply
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          POSTGRESQL_POD=$(oc get po --selector=name=postgres -o jsonpath='{..metadata.name}')
          
          if [ -z "$POSTGRESQL_POD" ];
          then
            echo Createing Postgresql Database Instance, Schema, and Tables  
            oc new-app postgresql-persistent -p=NAMESPACE=openshift -p=DATABASE_SERVICE_NAME=postgres -p=POSTGRESQL_USER=postgres -p=POSTGRESQL_PASSWORD=postgres -p=POSTGRESQL_DATABASE=todo -p=POSTGRESQL_VERSION=13-el8
            
            sleep 60
            oc wait --for=condition=Ready pods --timeout=360s --selector name=postgres
          
            POSTGRESQL_POD=$(oc get po --selector=name=postgres -o jsonpath={..metadata.name})
            oc cp "wls12214-todo-app-migration/scripts/01-database.sql" $POSTGRESQL_POD:/tmp
            oc cp "wls12214-todo-app-migration/scripts/02-schema.sql" $POSTGRESQL_POD:/tmp
            oc exec -ti $POSTGRESQL_POD -- /bin/bash -c "PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d postgres -a -f /tmp/01-database.sql"
            oc exec -ti $POSTGRESQL_POD -- /bin/bash -c "PGPASSWORD=postgres psql -h localhost -p 5432 -U postgres -d todo -a -f /tmp/02-schema.sql"
          else
            echo "Postgresql Database Already Deployed"
          fi
          echo -----------------------------------